config/routes.rb
Rails.application.routes.draw do
  
  

  

  resources :blogs do
    member do
        put :upvote
        put :downvote
        put :approve
        put :feature
        end 
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end

  end

  

  devise_for :users
  resources :users do

    member do
      get :edit_profile
      get :profile
      resources :profiles, only:[:update, :destroy]      
    end

  end
 
  resources :bvotes, only: [:create]
  resources :lists do
      member do
        put :upvote
        get :upvote
        put :downvote
        get :downvote
        put :approve
        put :feature
        end 
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select        
        get :reply
        put :upvote
        get :upvote
        put :downvote
        get :downvote
      end
    end
  end

  resources :polls do
      member do
        put :upvote
        put :downvote
        put :approve
        put :feature
      end
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end
  end


  resources :photos
  resources :pictures
	root 'home#index'

   resources :questions do
    member do
    put :upvote
    put :downvote
    put :approve 
    put :feature   
    end      
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end
  end

  
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord  
	  belongs_to :user
  	belongs_to :category
  	has_many :comments, as: :commentable, dependent: :destroy    
  	has_many :pictures, dependent: :destroy, inverse_of: :question
  	accepts_nested_attributes_for :pictures, allow_destroy: true
  	extend FriendlyId
  	friendly_id :title, use: [:finders, :slugged]
    acts_as_votable
    is_impressionable



self.per_page = 10


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :approve, :feature]
  before_action :check_user, only: [:edit, :update, :destroy]
  impressionist actions: [:show,:index]

  # GET /questions
  # GET /questions.json
  def index
    
    @questions = Question.where(approved: true).paginate(page: params[:page]).order('created_at DESC')

  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @pictures = @question.pictures.order('created_at ASC')

  
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.pictures.build
  end

  # GET /questions/1/edit
  def edit
    @question.pictures.order('created_at ASC')
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.build(question_params)
    

    respond_to do |format|
      if @question.save
        @question.user.increment!(:points, 3)
        format.html { redirect_to @question, notice: 'Soru başarılı bir şekilde oluşturuldu' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Soru başarılı bir şekilde güncellendi' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    @question.user.decrement!(:points, 3)
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Soru başarılı bir şekilde silindi' }
      format.json { head :no_content }

    end
  end


def upvote  #
  unless current_user == @question.user
   unless (current_user.voted_up_on? @question)
     @question.upvote_by current_user
     @question.user.increment!(:points, 1)   
    respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.js { render layout: false }
      end    
     end
   end
   end  

  def downvote   
      unless current_user == @question.user
   unless current_user.voted_down_on? @question
     @question.downvote_by current_user
     @question.user.decrement!(:points, 1)   
    respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.js { render layout: false }
      end    
     end
   end
  end


def approve
  if @question.approved?
    @question.update_attribute(:approved, false)
  else
    @question.update_attribute(:approved, true)
  end
  redirect_back(fallback_location: root_path)
end

def feature
  if @question.featured?
    @question.update_attribute(:featured, false)
  else
    @question.update_attribute(:featured, true)
  end
  redirect_back(fallback_location: root_path)
end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, :draft, :approved, :category_id, pictures_attributes:[:id, :image, :question_id, :ititle, :idescription, :_destroy])
    end

def check_user  
    redirect_to root_path, alert: "Buna yetkiniz yok üzgünüz." unless current_user == @question.user or current_user.admin?
  end  


def decrement!(attribute, by = 1)
  decrement(attribute, by).update_attribute(attribute, self[attribute])
end

def increment!(attribute, by = 1)
  increment(attribute, by).update_attribute(attribute, self[attribute])
end
  





end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit_form.html.slim
= simple_form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      h2 = "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      ul
        - @question.errors.full_messages.each do |message|
          li = message       

  .field    
    = f.input :title, label:"Soru başlığı:"
  .field       
    = f.input :body, as: :trix_editor, label:"Soru detayı"
  
  .field   
    = f.collection_select :category_id, Category.all, :id, :name, {prompt: "Kategori seçiniz"}
  
 
  table.question-picture-form
    tbody class="soru"      
      = f.fields_for :pictures do |picture|        
        = render 'picture_fields', f: picture
      
  .links= link_to_add_association 'Resim ekle', f, :pictures, class:"btn btn-info"
  

  = f.submit


coffee:
  $(document).on('page:change', ()->

  onAddFile = (event) ->
    file = event.target.files[0]
    url = URL.createObjectURL(file)

    thumbContainer = $(this).parent().siblings('div.thumb')

    if thumbContainer.find('img').length == 0
      thumbContainer.append('<img src="' + url + '" width="600" height="370" />')
    else
      thumbContainer.find('img').attr('src', url)

  # for redisplayed file inputs and file inputs in edit page
  $('input[type=file]').each(()->
      $(this).change(onAddFile)
  )

  # register event handler when new cocoon partial is inserted from link_to_add_association link
  $('body').on('cocoon:after-insert', (e, addedPartial) ->
    $('input[type=file]', addedPartial).change(onAddFile)
  )

  # tell cocoon where to insert partial
  $('a.add_fields').data('association-insertion-method', 'append')
  $('a.add_fields').data("association-insertion-node", 'table.question-picture-form tbody')
  )

app/views/questions/_form.html.slim
= simple_form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      h2 = "#{pluralize(@question.errors.count, "error")} Hata tespit edildiği için kaydedilemiyor:"
      ul
        - @question.errors.full_messages.each do |message|
          li = message       

  .field    
    = f.input :title, label:"Soru başlığı:"
  .field       
    = f.input :body, as: :trix_editor, label:"Soru detayı"
  
  .field   
    = f.collection_select :category_id, Category.all, :id, :name, {prompt: "Kategori seçiniz"}
  
 
  table.question-picture-form
    tbody class="soru"     
          
      
  .links= link_to_add_association 'Resim ekle', f, :pictures, class:"btn btn-info"
  
  hr
  = f.submit value: "Soru ekle", class: "btn btn-primary btn-lg"


coffee:
  $(document).on('page:change', ()->

  onAddFile = (event) ->
    file = event.target.files[0]
    url = URL.createObjectURL(file)

    thumbContainer = $(this).parent().siblings('div.thumb')

    if thumbContainer.find('img').length == 0
      thumbContainer.append('<img src="' + url + '" width="600" height="370" />')
    else
      thumbContainer.find('img').attr('src', url)

  # for redisplayed file inputs and file inputs in edit page
  $('input[type=file]').each(()->
      $(this).change(onAddFile)
  )

  # register event handler when new cocoon partial is inserted from link_to_add_association link
  $('body').on('cocoon:after-insert', (e, addedPartial) ->
    $('input[type=file]', addedPartial).change(onAddFile)
  )

  # tell cocoon where to insert partial
  $('a.add_fields').data('association-insertion-method', 'append')
  $('a.add_fields').data("association-insertion-node", 'table.question-picture-form tbody')
  )

app/views/questions/_picture_fields.html.slim
div.nested-fields style="background-color:lightpink"
  div   	  
    = f.file_field :image, class:"form-control"
    = f.hidden_field :image_cache, :value => f.object.image_cache
  div.thumb
   - if f.object.image_url.present?
     = image_tag f.object.image_url
  br   
  div.description   
   	= f.input :idescription, label:"Resim açıklaması(Boş bırakabilirsiniz.)"
  
  div= link_to_remove_association "Resmi kaldır", f, class:"btn btn-danger btn-sm"
  hr

app/views/questions/_picture_fields.html_yedek.slim
div.nested-fields style="background-color:lightblue"
  div 
  	= f.input :ititle, label: "Madde Başlığı"     
    = f.file_field :image, style: "background-color:lightblue", class:"form-control"
    = f.hidden_field :image_cache, :value => f.object.image_cache
  div.thumb
   - if f.object.image_url.present?
     = image_tag f.object.image_url
  div.description   
   	= f.input :idescription, label:"Soru detayı"
  
  div= link_to_remove_association "Resmi kaldır", f, class:"btn btn-danger btn-sm"
  hr

app/views/questions/_qdesc_fields.html.slim
.nested-fields
  div 
  	= f.input :description, label: "Detay:"
  	= link_to_remove_association "Detayı kaldır", f, class: "btn btn-danger btn-sm"

app/views/questions/_qtitle_fields.html.slim
.nested-fields
  	= f.input :title, label: "Başlık"
  	= link_to_remove_association "Başlığı kaldır", f, class: "btn btn-danger btn-sm"

app/views/questions/downvote.js.erb
$('.downvotes-count').html("<%= @question.get_downvotes.size %>")
$('.upvotes-count').html("<%= @question.get_upvotes.size %>")

app/views/questions/edit.html.slim
h1 Soru Düzenleme

== render 'edit_form'

=> link_to 'Show', @question
'|
=< link_to 'Back', questions_path

app/views/questions/index.html.slim
  
  - @questions.each do |question|
        # class="card mb-4"
          # class="card-header"
            .row
              .col-md-auto
                = image_tag(question.user.profile.avatars.last.image_url(:icon)) 
              .col-md
                 = link_to "#{question.user.username}", profile_user_path(question.user), class:"badge badge-info badge-sm"
                
                  
          # class="card-body"
            .row
              - if question.pictures.present?
                .col-md-6
                  h3 = link_to question.title, question_path(question)
                  = sanitize question.body.truncate(200, separator: ' ')              
                .col-md-6  
                  = image_tag question.pictures.order('created_at ASC').first.image_url(:thumb) if question.pictures.present?
                  br
                  span class="badge badge-info" = "#{question.category.name}"
              - else
                .col-md
                  h3 = link_to question.title, question_path(question)
                  br                
                  = sanitize question.body.truncate(200, separator: ' ')    

          # class="card-footer" 
            -if user_signed_in?
              -if current_user.admin? or current_user == question.user           
                = link_to 'Düzenle', edit_question_path(question), class:"btn btn-warning btn-sm"
                = link_to 'Sil', question, data: { confirm: 'Are you sure?' }, method: :delete, class:"btn btn-danger btn-sm"
  .pagination-center
    = will_paginate @questions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer               

app/views/questions/new.html.slim
h1 Yeni Soru

== render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.slim
h1.mt-4
  = @question.title  
p.lead
  = link_to image_tag(@question.user.profile.avatars.last.image_url(:icon)), @question.user
  = " | "
  = link_to @question.user.username, @question.user 
  |  tarafından paylaşıldı.
hr
p
  = localize(@question.created_at, format: :long)
  = " | #{@question.impressionist_count} kez görüntülendi." 
hr
= sanitize @question.body
hr
- if @question.pictures.present?
  - @question.pictures.each do |picture|
    img.img-fluid.rounded[src="#{picture.image_url(:medium)}"]
    div
      = picture.idescription      


- if user_signed_in? 
  - if current_user.admin? or current_user == @question.user
    p
      = link_to 'Edit', edit_question_path(@question)
      = " | "
      = link_to 'Destroy', @question, data: { confirm: 'Bu paylaşım silinecek Emin misiniz?' }, method: :delete
  = link_to upvote_question_path, class: "btn btn-outline-primary btn-sm", method: :put, remote: true do
    i.fa.fa-thumbs-up
    span.badge.badge-light.upvotes-count
      =  @question.get_upvotes.size
  = button_to downvote_question_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
    i.fa.fa-thumbs-down
    span.badge.badge-light.downvotes-count
      =  @question.get_downvotes.size
  - if current_user.admin?
    - if @question.approved?     
      = button_to approve_question_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
        i.fa.fa-ban
          span.badge
            |Onayı kaldır   
    - else  
     = button_to approve_question_path, class: "btn btn-outline-success btn-sm", method: :put, remote: true do
      i.fa.fa-minus-square
        span.badge
          |Onayla   
    - if @question.featured?     
        = button_to feature_question_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
          i.fa.fa-ban
            span.badge
              |Vitrinden kaldır   
    - else  
     = button_to feature_question_path, class: "btn btn-outline-success btn-sm", method: :put, remote: true do
      i.fa.fa-minus-square
        span.badge
          |Vitrine koy 

= render "comments/widget", commentable: @question  


 

app/views/questions/upvote.js.erb
$('.downvotes-count').html("<%= @question.get_downvotes.size %>")
$('.upvotes-count').html("<%= @question.get_upvotes.size %>")

app/views/questions/yedek.html.erb
  div class="fileinput fileinput-new" data-provides="fileinput"
	  div class="fileinput-new thumbnail" style="width: 200px; height: 150px;"
	    	img data-src="holder.js/100%x100%" alt="..."  
	  div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"		  
		    	span class="btn btn-default btn-file"
		    		span class="fileinput-new" Select image
		    			span class="fileinput-exists" Change
		    				input type="file" name="..."
		    	a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput" Remove



		    	= f.simple_fields_for :pictures do |picture|
        = render 'picture_fields', f: picture