config/routes.rb
Rails.application.routes.draw do
  
  

  

  resources :blogs do
    member do
        put :upvote
        put :downvote
        put :approve
        put :feature
        end 
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end

  end

  

  devise_for :users
  resources :users do

    member do
      get :edit_profile
      get :profile
      resources :profiles, only:[:update, :destroy]      
    end

  end
 
  resources :bvotes, only: [:create]
  resources :lists do
      member do
        put :upvote
        get :upvote
        put :downvote
        get :downvote
        put :approve
        put :feature
        end 
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select        
        get :reply
        put :upvote
        get :upvote
        put :downvote
        get :downvote
      end
    end
  end

  resources :polls do
      member do
        put :upvote
        put :downvote
        put :approve
        put :feature
      end
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end
  end


  resources :photos
  resources :pictures
	root 'home#index'

   resources :questions do
    member do
    put :upvote
    put :downvote
    put :approve 
    put :feature   
    end      
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end
  end

  
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :listmages, dependent: :destroy, inverse_of: :list
  accepts_nested_attributes_for :listmages, allow_destroy: true
  has_many :comments, as: :commentable, dependent: :destroy
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_votable
  is_impressionable
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :set_list, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :approve, :feature]
  impressionist actions: [:show,:index]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @listmages = @list.listmages.order('created_at ASC')
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @list.listmages.order('created_at ASC')
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        @list.user.increment!(:points, 5)
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      @list.user.decrement!(:points, 5)
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


def upvote  #
  unless current_user == @list.user
   unless (current_user.voted_up_on? @list)
     @list.upvote_by current_user
     @list.user.increment!(:points, 1)   
    respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.js { render layout: false }
      end    
     end
   end
   end  

  def downvote 
      unless current_user == @list.user
   unless current_user.voted_down_on? @list
     @list.downvote_by current_user
     @list.user.decrement!(:points, 1)  
    respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.js { render layout: false }
      end    
     end
   end
  end


def approve
  if @list.approved?
    @list.update_attribute(:approved, false)
  else
    @list.update_attribute(:approved, true)
  end
  redirect_back(fallback_location: root_path)
end

def feature
  if @list.featured?
    @list.update_attribute(:featured, false)
  else
    @list.update_attribute(:featured, true)
  end
  redirect_back(fallback_location: root_path)
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description, :user_id, :category_id, listmages_attributes:[:image, :title, :description, :_destroy])
    end



    def decrement!(attribute, by = 1)
  decrement(attribute, by).update_attribute(attribute, self[attribute])
end

def increment!(attribute, by = 1)
  increment(attribute, by).update_attribute(attribute, self[attribute])
end

    
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_edit_form.html.slim
= simple_form_for @list do |f|
  - if @list.errors.any?
    #error_explanation
      h2 = "#{pluralize(@list.errors.count, "error")} Hata tespit edildiği için kaydedilemiyor:"
      ul
        - @list.errors.full_messages.each do |message|
          li = message       

  .field    
    = f.input :title, label:"Liste başlığı:"
  .field       
    = f.input :description, as: :trix_editor, label:"Liste açıklaması"
  
  .field   
    = f.collection_select :category_id, Category.all, :id, :name, {prompt: "Kategori seçiniz"}
  
 
  table.list-picture-form
    tbody class="liste"     
      = f.fields_for :listmages do |listmage|        
        = render 'listmage_fields', f: listmage        
      
  .links= link_to_add_association 'Resim ekle', f, :listmages, class:"btn btn-info"
  
  hr
  = f.submit class: "btn btn-primary btn-lg"


coffee:
  $(document).on('page:change', ()->

  onAddFile = (event) ->
    file = event.target.files[0]
    url = URL.createObjectURL(file)

    thumbContainer = $(this).parent().siblings('div.thumb')

    if thumbContainer.find('img').length == 0
      thumbContainer.append('<img src="' + url + '" width="600" height="370" />')
    else
      thumbContainer.find('img').attr('src', url)

  # for redisplayed file inputs and file inputs in edit page
  $('input[type=file]').each(()->
      $(this).change(onAddFile)
  )

  # register event handler when new cocoon partial is inserted from link_to_add_association link
  $('body').on('cocoon:after-insert', (e, addedPartial) ->
    $('input[type=file]', addedPartial).change(onAddFile)
  )

  # tell cocoon where to insert partial
  $('a.add_fields').data('association-insertion-method', 'append')
  $('a.add_fields').data("association-insertion-node", 'table.list-picture-form tbody')
  )

app/views/lists/_form.html.slim
= simple_form_for @list do |f|
  - if @list.errors.any?
    #error_explanation
      h2 = "#{pluralize(@list.errors.count, "error")} Hata tespit edildiği için kaydedilemiyor:"
      ul
        - @list.errors.full_messages.each do |message|
          li = message       

  .field    
    = f.input :title, label:"Liste başlığı:"
  .field       
    = f.input :description, as: :trix_editor, label:"Liste açıklaması"
  
  .field   
    = f.collection_select :category_id, Category.all, :id, :name, {prompt: "Kategori seçiniz"}
  
 
  table.list-picture-form
    tbody class="liste"          
      
  .links= link_to_add_association 'Resim ekle', f, :listmages, class:"btn btn-info"
  
  hr
  = f.submit class: "btn btn-primary btn-lg"


coffee:
  $(document).on('page:change', ()->

  onAddFile = (event) ->
    file = event.target.files[0]
    url = URL.createObjectURL(file)

    thumbContainer = $(this).parent().siblings('div.thumb')

    if thumbContainer.find('img').length == 0
      thumbContainer.append('<img src="' + url + '" width="600" height="370" />')
    else
      thumbContainer.find('img').attr('src', url)

  # for redisplayed file inputs and file inputs in edit page
  $('input[type=file]').each(()->
      $(this).change(onAddFile)
  )

  # register event handler when new cocoon partial is inserted from link_to_add_association link
  $('body').on('cocoon:after-insert', (e, addedPartial) ->
    $('input[type=file]', addedPartial).change(onAddFile)
  )

  # tell cocoon where to insert partial
  $('a.add_fields').data('association-insertion-method', 'append')
  $('a.add_fields').data("association-insertion-node", 'table.list-picture-form tbody')
  )

app/views/lists/_liste.html.slim
  h1.mt-4
    = @list.title  
  p.lead
    = link_to image_tag(@list.user.profile.avatars.last.image_url(:icon)), @list.user
    = " | "
    = link_to @list.user.username, @list.user 
    |  tarafından paylaşıldı.
  hr
  p
    = localize(@list.created_at, format: :long)
  hr
  - count = 1
  - @listmages.each do |listmage|    
    h3 = count.to_s + "- " + listmage.title
    .thumb= image_tag listmage.image_url(:medium)
    = sanitize listmage.description 
    - count = count + 1   
    = sanitize @list.description
  - if user_signed_in? && (current_user.admin? or current_user == @list.user)
    p
      = link_to 'Edit', edit_list_path(@list)
      = " | "
      = link_to 'Destroy', @list, data: { confirm: 'Bu paylaşım silinecek Emin misiniz?' }, method: :delete

app/views/lists/_listmage_fields.html.slim
div.nested-fields style="background-color:lightpink" 
  div
    = f.input :title, label: "Madde Başlığı"
    = f.file_field :image, class:"form-control"
    = f.hidden_field :image_cache, :value => f.object.image_cache
  div.thumb
   - if f.object.image_url.present?
     = image_tag f.object.image_url
  br   
  div.description   
   	= f.input :description, label:"Resim açıklaması(Boş bırakabilirsiniz.)"
  
  div= link_to_remove_association "Resmi kaldır", f, class:"btn btn-danger btn-sm"
  hr

app/views/lists/downvote.js.erb
$('.downvotes-count').html("<%= @list.get_downvotes.size %>")
$('.upvotes-count').html("<%= @list.get_upvotes.size %>")

app/views/lists/edit.html.slim
h1 Editing list

== render 'edit_form'

=> link_to 'Show', @list
'|
=< link_to 'Back', lists_path

app/views/lists/index.html.slim
- @lists.each do |list|
    # class="card-deck mb-3 text-left"
      # class="card mb-4"
        # class="card-header"
          .row
            .col-md-auto
              = link_to list.title, list_path(list)
            .col-md
              span class="badge badge-info" = "#{list.user.username}"
                
        # class="card-body"
          = sanitize list.description
          = image_tag list.listmages.order('created_at ASC').first.image_url(:thumb) if list.listmages.present?
             
          hr 

          span class="badge badge-info" = "Tag(category for now):   #{list.category.name}"
        # class="card-footer" 
          -if user_signed_in?
            -if current_user.admin? or current_user == list.user           
              = link_to 'Düzenle', edit_list_path(list), class:"btn btn-warning btn-sm"
              = link_to 'Sil', list, data: { confirm: 'Are you sure?' }, method: :delete, class:"btn btn-danger btn-sm"

app/views/lists/new.html.slim
h1 New list

== render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.slim
h1.mt-4
  = @list.title 
  = sanitize @list.description 
p.lead
  = link_to image_tag(@list.user.profile.avatars.last.image_url(:icon)), @list.user
  = " | "
  = link_to @list.user.username, @list.user 
  |  tarafından paylaşıldı.
hr
p
  = localize(@list.created_at, format: :long)
  = " | #{@list.impressionist_count} kez görüntülendi." 
hr
- count = 1
- @listmages.each do |listmage|    
  h3 = count.to_s + "- " + listmage.title
  .thumb= image_tag listmage.image_url(:medium)
  = sanitize listmage.description 
  - count = count + 1   
  
- if user_signed_in? 
  - if current_user.admin? or current_user == @list.user
    p
      = link_to 'Edit', edit_list_path(@list)
      = " | "
      = link_to 'Destroy', @list, data: { confirm: 'Bu paylaşım silinecek Emin misiniz?' }, method: :delete
  = link_to upvote_list_path, class: "btn btn-outline-primary btn-sm", method: :put, remote: true do
    i.fa.fa-thumbs-up
    span.badge.badge-light.upvotes-count
      =  @list.get_upvotes.size
  = button_to downvote_list_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
    i.fa.fa-thumbs-down
    span.badge.badge-light.downvotes-count
      =  @list.get_downvotes.size 
  - if current_user.admin?
    - if @list.approved?     
      = button_to approve_list_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
        i.fa.fa-ban
          span.badge
            |Onayı kaldır   
    - else  
     = button_to approve_list_path, class: "btn btn-outline-success btn-sm", method: :put, remote: true do
      i.fa.fa-minus-square
        span.badge
          |Onayla   
    - if @list.featured?     
        = button_to feature_list_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
          i.fa.fa-ban
            span.badge
              |Vitrinden kaldır   
    - else  
     = button_to feature_list_path, class: "btn btn-outline-success btn-sm", method: :put, remote: true do
      i.fa.fa-minus-square
        span.badge
          |Vitrine koy 

= render "comments/widget", commentable: @list  

app/views/lists/showyedekhtml.slim
.col-md-8
  h1.mt-4
    = @list.title  
  p.lead
    = link_to image_tag(@list.user.profile.avatars.last.image_url(:icon)), @list.user
    = " | "
    = link_to @list.user.username, @list.user 
    |  tarafından paylaşıldı.
  hr
    = link_to "#{@list.user.username}", @list.user, class:"btn btn-info btn-sm"
  p

    = sanitize @list.description
  p

    = @list.user.email
  p

    span class="badge badge-info" = "#{@list.category.name}"
  - count = 1
  - @listmages.each do |listmage|
  	
    h3 = count.to_s + "- " + listmage.title
    .thumb= image_tag listmage.image_url(:medium)
    = listmage.description 
    - count = count + 1 
    => link_to 'Edit', edit_list_path(@list)
    '|
    =< link_to 'Back', lists_path
  .row
    = render "comments/widget", commentable: @list    

app/views/lists/upvote.js.erb
$('.downvotes-count').html("<%= @list.get_downvotes.size %>")
$('.upvotes-count').html("<%= @list.get_upvotes.size %>")