config/routes.rb
Rails.application.routes.draw do
  
  

  

  resources :blogs do
    member do
        put :upvote
        put :downvote
        put :approve
        put :feature
        end 
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end

  end

  

  devise_for :users
  resources :users do

    member do
      get :edit_profile
      get :profile
      resources :profiles, only:[:update, :destroy]      
    end

  end
 
  resources :bvotes, only: [:create]
  resources :lists do
      member do
        put :upvote
        get :upvote
        put :downvote
        get :downvote
        put :approve
        put :feature
        end 
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select        
        get :reply
        put :upvote
        get :upvote
        put :downvote
        get :downvote
      end
    end
  end

  resources :polls do
      member do
        put :upvote
        put :downvote
        put :approve
        put :feature
      end
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end
  end


  resources :photos
  resources :pictures
	root 'home#index'

   resources :questions do
    member do
    put :upvote
    put :downvote
    put :approve 
    put :feature   
    end      
    resources :comments, except: [:index, :new, :show] do
      member do
        put :select
        get :reply
        put :upvote        
        put :downvote
      end
    end
  end

  
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
	has_many :blog_images, dependent: :destroy
	accepts_nested_attributes_for :blog_images, allow_destroy: true
	has_many :photos, dependent: :destroy
	accepts_nested_attributes_for :photos, allow_destroy: true
  belongs_to :user
  belongs_to :category
  extend FriendlyId
  friendly_id :title, use: [:finders, :slugged]
  acts_as_votable
  has_many :comments, as: :commentable, dependent: :destroy
  is_impressionable
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
   before_action :authenticate_user!, except:[:index, :show]
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :approve, :feature]
  impressionist actions: [:show,:index]
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.where(approved: true).paginate(page: params[:page]).order('created_at DESC')
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    
  end



  # GET /blogs/new
  def new
     @blog = Blog.new
     @blog.blog_images.build     
  

  end

  # GET /blogs/1/edit
  def edit
    @blog.blog_images.build 
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        @blog.user.increment!(:points, 5) 
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
        
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    @blog.user.decrement!(:points, 5) 
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


def upvote  #
  unless current_user == @blog.user
   unless (current_user.voted_up_on? @blog)
     @blog.upvote_by current_user
     @blog.user.increment!(:points, 1) 
    respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.js { render layout: false }
      end    
     end
   end
   end  

  def downvote 
      unless current_user == @blog.user
   unless current_user.voted_down_on? @blog
     @blog.downvote_by current_user
     @blog.user.decrement!(:points, 1)   
    respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.js { render layout: false }
      end    
     end
   end
  end

def approve
  if @blog.approved?
    @blog.update_attribute(:approved, false)
  else
    @blog.update_attribute(:approved, true)
  end
  redirect_back(fallback_location: root_path)
  
end

def feature
  if @blog.featured?
    @blog.update_attribute(:featured, false)
  else
    @blog.update_attribute(:featured, true)
  end
  redirect_back(fallback_location: root_path)
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :published, :approved, :featured, :user_id, :category_id, blog_images_attributes:[:image, :_destroy])
    end
end



def decrement!(attribute, by = 1)
  decrement(attribute, by).update_attribute(attribute, self[attribute])
end

def increment!(attribute, by = 1)
  increment(attribute, by).update_attribute(attribute, self[attribute])
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.slim
= simple_form_for(@blog) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs 
    = f.fields_for :blog_images do|ff| 
      = ff.file_field :image
    = f.input :title
    = f.input :body, as: :trix_editor    
    = f.association :category

  .form-actions
    = f.button :submit

app/views/blogs/downvote.js.erb
$('.downvotes-count').html("<%= @blog.get_downvotes.size %>")
$('.upvotes-count').html("<%= @blog.get_upvotes.size %>")

app/views/blogs/edit.html.slim
h1 Editing blog

== render 'form'

=> link_to 'Show', @blog
'|
=< link_to 'Back', blogs_path

app/views/blogs/index.html.slim
- @blogs.each do |blog|
  .row
    h2.card-title
      = link_to blog.title, blog
  .row
    col-md-7
      - if blog.blog_images.present?
        img.img-fluid.rounded[src="#{blog.blog_images.last.image_url(:thumb)}"]
      hr
    .col-md-8
      .card-body 
        = sanitize blog.body.truncate(160, separator: ' ')
        br
        = link_to 'Devamını oku', blog, class:"btn btn-primary"
  .row.card-footer.text-muted
    = localize(blog.created_at, format: :long)
    - if user_signed_in? and (current_user.admin? or current_user == blog.user)
      p
        = link_to 'Edit', edit_blog_path(blog)
        = link_to 'Destroy', blog, data: { confirm: 'Are you sure?' }, method: :delete
    = " |  #{blog.impressionist_count} kez görüntülendi."   
  hr        
= will_paginate @blogs, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/blogs/new.html.slim
h1 New blog

== render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.slim
h1.mt-4
  = @blog.title  
p.lead
  = link_to image_tag(@blog.user.profile.avatars.last.image_url(:icon)), @blog.user
  = " | "
  = link_to @blog.user.username, @blog.user 
  |  tarafından paylaşıldı.
hr
p
  = localize(@blog.created_at, format: :long)
  = " | #{@blog.impressionist_count} kez görüntülendi." 
hr
- if @blog.blog_images.present?
  - @blog.blog_images.each do |image|
  	img.img-fluid.rounded[src="#{image.image_url(:medium)}"]
hr
= sanitize @blog.body
- if user_signed_in? 
  - if current_user.admin? or current_user == @blog.user
    p
      = link_to 'Edit', edit_blog_path(@blog)
      = " | "
      = link_to 'Destroy', @blog, data: { confirm: 'Bu paylaşım silinecek Emin misiniz?' }, method: :delete
  = link_to upvote_blog_path, class: "btn btn-outline-primary btn-sm", method: :put, remote: true do
    i.fa.fa-thumbs-up
    span.badge.badge-light.upvotes-count
      =  @blog.get_upvotes.size
  = button_to downvote_blog_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
    i.fa.fa-thumbs-down
    span.badge.badge-light.downvotes-count
      =  @blog.get_downvotes.size
  - if current_user.admin?
    - if @blog.approved?     
      = button_to approve_blog_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
        i.fa.fa-ban
          span.badge
            |Onayı kaldır   
    - else  
     = button_to approve_blog_path, class: "btn btn-outline-success btn-sm", method: :put, remote: true do
      i.fa.fa-check
        span.badge
          |Onayla 
    - if @blog.featured?     
        = button_to feature_blog_path, class: "btn btn-outline-danger btn-sm", method: :put, remote: true do
          i.fa.fa-ban
            span.badge
              |Vitrinden kaldır   
    - else  
     = button_to feature_blog_path, class: "btn btn-outline-success btn-sm", method: :put, remote: true do
      i.fa.fa-check
        span.badge
          |Vitrine koy          
          
= render "comments/widget", commentable: @blog      

app/views/blogs/upvote.js.erb
$('.downvotes-count').html("<%= @blog.get_downvotes.size %>")
$('.upvotes-count').html("<%= @blog.get_upvotes.size %>")